### ISSUE TITLE
Errno 111 Connection refused

### ISSUE THREAD

**Issue by XiaoKe89** [attzonko/mmpy_bot#358] opened 2022-11-25 08:25 UTC
I've been trying to get a bot up and running and I keep getting an error that says: httpx.ConnectError: [Errno 111] Connection refused.

I'm sure I configured something wrong or forgot to change a setting somewhere but I'm not sure what.

I'm running my mattermost instance through an Unraid Docker container and then I set up a ubuntu server VM to host the bot (since generally with Unraid you don't want programs running outside of Docker containers). My mattermost is also behind a caddy reverse proxy which I assume makes a difference.

I've triple checked all the settings I can think of and can't figure it out so any help would be much appreciated.

**Comment by unode** [comment] 2022-11-25 14:43
It doesn't sound like the problem is specific to mmpy_bot.
Can you `curl` the IP and port where mattermost is running?

**Comment by unode** [comment] 2022-11-25 14:53
And if you tried the above already, are you using `SSL_VERIFY=False`?
You need it if connecting to a Mattermost server running at `http://` or `https://` (when using a self signed certificate).

See example at: 

https://github.com/attzonko/mmpy_bot/blob/7f97986c6d07552e043af6b235e8f007d202cd87/tests/integration_tests/utils.py#L67

**Comment by XiaoKe89** [comment] 2022-11-25 23:15
> It doesn't sound like the problem is specific to mmpy_bot. Can you `curl` the IP and port where mattermost is running?

Yeah I'm guessing I'm either missing something or it might be the VM. I'm still pretty new to all of this what do you mean by curl the IP and port?

and to answer the second question I tried setting SSL_Verify to both true and false and both result in the same error

**Comment by unode** [comment] 2022-11-26 12:05
`curl` is a command-line tool that can be used to download content.
The test was meant to figure out if Mattermost's API on your server could be contacted.
If it can't there's something missing in your configuration and therefore not a mmpy_bot problem.
Hope you can figure that out.

**Comment by unode** [comment] 2023-01-23 11:58
Has this been solved meanwhile?

**Comment by unode** [comment] 2023-03-06 09:58
Closed as abandoned. Feel free to reopen if still relevant.

**Closed by unode** 2023-03-06 09:58 UTC
Labels: question
