### ISSUE TITLE
Configuration mmpy-bot with mattermost 

### ISSUE THREAD

**Issue by dev1236** [attzonko/mmpy_bot#334] opened 2022-08-18 08:28 UTC
**Describe the bug**
failure to establish websocket like : [mattermostdriver.websocket][WARNING] Failed to establish websocket connection: server rejected WebSocket connection: HTTP 200

**How To Reproduce**
Give us simple steps to reproduce the behavior:

**Expected behavior**

**Operating Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Linux, MacOS]
 - Python Version: [e.g. 3.10]
 - Mattermost Version: [e.g. Latest] that is on server not in matternost-desktop
 - mmpy_bot Version: [e.g. 1.2.1]

**Additional context**
I jhave craeted mattermost bot account and One chatbot channel and i configure the mmpy-bot with mattermost url , token , port as well as bot_team . 
![image](https://user-images.githubusercontent.com/69010689/185341316-1195e6a6-20cf-4ff1-802b-ed1ea46d4901.png)

**Comment by attzonko** [comment] 2022-08-21 22:38
There was a recent fix to the mattermostdriver package related to websocket connection. Could you try with the latest mattermostdriver from the HEAD of that repo?

**Comment by unode** [comment] 2022-08-29 09:09
As we are now using a different driver, could you please re-test if the latest version from the `main` branch still displays this bug and report here?
Thanks!

**Comment by cristianjuve** [comment] 2022-09-13 14:47
We're receiving the same issue after upgrade to mattermost 7.1.2 from 5.38.2.
Error with mmpy-bot=2.0.2
![Captura de pantalla 2022-09-13 a les 16 35 13](https://user-images.githubusercontent.com/18593495/189929926-cf0da6a2-9749-40d6-b9c0-612fd8f0d08b.png)
If we enable debug mode then it works.

Error with mmpy-bot=2.1.0
![Captura de pantalla 2022-09-13 a les 16 37 02](https://user-images.githubusercontent.com/18593495/189930283-e6fe8db2-5c56-4d4a-850f-b4de486d13cb.png)
In this case if we enable debug mode it doesn't work.

We're using a custom plugin and we don't understand what's the function that is failing on our code. I share with you part of our code to try to find where is the issue.
![Captura de pantalla 2022-09-13 a les 16 40 36](https://user-images.githubusercontent.com/18593495/189932134-a6b45ef3-8883-4d37-a47a-ec88dc2b709b.png)

Thanks!

**Comment by unode** [comment] 2022-09-13 15:07
In the first case, there's a problem in `mattermostdriver` that was since fixed but an upgrade is required.
Regarding the `plugin.initialize()` error in 2.1.0, there was an API change that introduced another argument.

See the difference between 2.0.2

https://github.com/attzonko/mmpy_bot/blob/641b918249b30e699038169dccab3e554dde2d70/mmpy_bot/plugins/base.py#L34 

and 2.1.0

https://github.com/attzonko/mmpy_bot/blob/641b918249b30e699038169dccab3e554dde2d70/mmpy_bot/plugins/base.py#L34

**Comment by unode** [comment] 2022-09-13 17:25
You can continue using:

```
plugins=[SealPlugin()]
```

but you need to update the signature of `def initialize(driver, plugin_manager, settings):` in your plugin.

You don't need to use your own `PluginManager` instance unless you want to customize/override its behavior.

**Comment by unode** [comment] 2022-09-13 17:46
Please see #306 for a follow up on the `mattermostdriver` issue.

I believe the issue is solved by https://github.com/embl-bio-it/python-mattermost-autodriver/commit/b699cb96fe686001751c4cfdd0e9b85662c4fc96 but a version of `mmpy_bot` that uses this fix hasn't been released yet.
Please try the latest code from the `main` branch and lets us know if the problem is gone.

I'm using it on Mattermost 7.1.2 without problems.

**Comment by cristianjuve** [comment] 2022-09-13 18:01
it works!! thnks! :)

**Comment by unode** [comment] 2022-09-13 18:12
Closing as resolved in `main`.

**Closed by unode** 2022-09-13 18:12 UTC
Labels: bug

**Comment by attzonko** [comment] 2022-09-13 21:06
Just made release 2.1.1 from the latest main

Thanks for confirming the fixes work for you @cristianjuve
