### ISSUE TITLE
RuntimeError: this event loop is already running.

### ISSUE THREAD

**Issue by nosfirlabs** [attzonko/mmpy_bot#379] opened 2023-03-04 19:28 UTC
running latest bot ver with fastAPI throws this

[03/04/2023 20:26:48][mmpy.bot][INFO] Starting bot Bot.
[03/04/2023 20:26:48][mmpy.bot][INFO] Stopping bot.
[03/04/2023 20:26:48][mmpy.threadpool][INFO] Stopping threadpool, waiting for threads...
[03/04/2023 20:26:48][mmpy.threadpool][INFO] Scheduler thread started.
[03/04/2023 20:26:48][mmpy.threadpool][INFO] Scheduler thread stopped.
[03/04/2023 20:26:48][mmpy.threadpool][INFO] Threadpool stopped.
Process SpawnProcess-5:
RuntimeError: this event loop is already running.

**Comment by unode** [comment] 2023-03-06 09:42
Can you provide a minimal reproducible example?

**Comment by Samcro5C** [comment] 2023-07-07 15:27
Hello @unode 
I am encountering the same problem when trying to reproduce the minimal example as described [here](https://mmpy-bot.readthedocs.io/en/latest/plugins.html). 
Software versions:
mmpy-bot: 2.1.3
python: 3.10.11
Mattermost: 7.10.2

```
from mmpy_bot import Bot, Settings
from mmpy_bot import Plugin, listen_to
from mmpy_bot import Message

class MyPlugin(Plugin):
    @listen_to("wake up")
    async def wake_up(self, message: Message):
        self.driver.reply_to(message, "I'm awake!")

bot = Bot(
    settings=Settings(
        MATTERMOST_URL = "<my_url>",
        MATTERMOST_PORT = 443,
        MATTERMOST_API_PATH = '/api/v4',
        BOT_TOKEN = "<my_token>",
        BOT_TEAM = "<my_team>",
        SSL_VERIFY = True,
    ),  # Either specify your settings here or as environment variables.
    plugins=[MyPlugin()],  # Add your own plugins here.
)
bot.run()
```

The error is raised in bot.run(), producing the following traceback
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[14], line 1
----> 1 bot.run()

File C:\ProgramData\Miniforge3\envs\test\lib\site-packages\mmpy_bot\bot.py:128, in Bot.run(self)
    125     self.plugin_manager.start()
    127     # Start listening for events
--> 128     self.event_handler.start()
    130 except KeyboardInterrupt as e:
    131     raise e

File C:\ProgramData\Miniforge3\envs\yann\lib\site-packages\mmpy_bot\event_handler.py:35, in EventHandler.start(self)
     33 def start(self):
     34     # This is blocking, will loop forever
---> 35     self.driver.init_websocket(self._handle_event)

File C:\ProgramData\Miniforge3\envs\test\lib\site-packages\mattermostautodriver\driver.py:152, in Driver.init_websocket(self, event_handler, websocket_cls)
    150 self.websocket = websocket_cls(self.options, self.client.token)
    151 loop = asyncio.get_event_loop()
--> 152 loop.run_until_complete(self.websocket.connect(event_handler))
    153 return loop

File C:\ProgramData\Miniforge3\envs\test\lib\asyncio\base_events.py:625, in BaseEventLoop.run_until_complete(self, future)
    614 """Run until the Future is done.
    615 
    616 If the argument is a coroutine, it is wrapped in a Task.
   (...)
    622 Return the Future's result, or raise its exception.
    623 """
    624 self._check_closed()
--> 625 self._check_running()
    627 new_task = not futures.isfuture(future)
    628 future = tasks.ensure_future(future, loop=self)

File C:\ProgramData\Miniforge3\envs\test\lib\asyncio\base_events.py:584, in BaseEventLoop._check_running(self)
    582 def _check_running(self):
    583     if self.is_running():
--> 584         raise RuntimeError('This event loop is already running')
    585     if events._get_running_loop() is not None:
    586         raise RuntimeError(
    587             'Cannot run the event loop while another loop is running')

RuntimeError: This event loop is already running

**Comment by unode** [comment] 2023-07-07 16:41
I can't reproduce it locally. Your code snippet works fine here but I'm not on Windows.

Can you add info on how you are launching the bot?
Also, do you have a mattermost server without SSL you could test against?

**Comment by Samcro5C** [comment] 2023-07-10 08:39
Thanks @unode for the fast reply. The hint with how I launched the bot made me check my code in a pure python script and there it works fine. Before I was launching the bot from a jupyter notebook, as I also planned to write direct messages from jupyter when a cell has finished. But so far I am not sure if this is a feature provided by mmpy_bot, because I would not be listening and reacting to a user's input but writing messages directly to a user. I saw that there is a method bot.driver.direct_message() but this requires to know the receiver_id, which I do not know.

**Comment by attzonko** [comment] 2023-07-18 15:22
Let me clarify just to make sure I understood the use case you are describing. You plan to manually respond as if you are the bot user? The way the bot is intended to work is to listen for triggers coming from all users in a channel and providing an automated response (no human interaction).

**Comment by Samcro5C** [comment] 2023-07-19 13:53
It is still supposed to be an automated message but it should be triggered from python code, hence not reacting to a user message in a mattermost channel but sending a (direct) message in the first place. For instance, I start a computation in python which might take several hours to days, then I would like to get a notification if an exception has occured or when it has finished, that everything has terminated successfully. I solved the original problem by not using jupyter for this but initialize a bot directly from a python script and use the driver to send a direct message (I could get my own user id from a mattermost server administrator).

**Comment by unode** [comment] 2023-07-19 14:09
I don't think you want mmpy_bot for what you described but simply to use one of the existing mattermost drivers directly.

For instance, have a look at [`python-mattermost-autodriver`](https://embl-bio-it.github.io/python-mattermost-autodriver/) and the example on the landing page.

mmpy_bot is a framework that is designed to run as a daemon, not embedded in other processes.

**Comment by unode** [comment] 2023-07-21 15:46
Re-reading your message I noticed you mentioned Jupyter. This likely means that you are trying to run mmpy_bot from a jupyter kernel, which already runs a loop to listen to Jupyter cell execution requests. Even there my previous suggestion likely won't work.

You need an entirely different system. Possibly to run the bot as a dedicated process elsewhere, and to use some other mechanism to let the bot know it needs to send a notification. You could use the builtin [webhook listener support](https://mmpy-bot.readthedocs.io/en/latest/plugins.html#webhook-listener) for that, a database or some other solution.

As running the bot iin a jupyter kernel is not a supported use-case, I will close this issue. Please feel free to re-open if you encounter this error in a regular standalone python process.

**Closed by unode** 2023-07-21 15:46 UTC
Labels: wontfix
