### ISSUE TITLE
Problem Connecting wss mattermost Bot

### ISSUE THREAD

**Issue by caruch** [attzonko/mmpy_bot#306] opened 2022-05-16 16:35 UTC
>**Describe the bug**
When trying to connect to mattermost via SSL, connection works, but connection to wss fails with the following message

[05/16/2022 13:31:16][mmpy.bot][INFO] Starting bot Bot.
[05/16/2022 13:31:16][mmpy.threadpool][INFO] Scheduler thread started.
[2022-05-16 13:31:16,019][mmpy.bot][INFO] Starting bot Bot.
[2022-05-16 13:31:16,022][mmpy.threadpool][INFO] Scheduler thread started.
[2022-05-16 13:31:16,064][mattermostdriver.websocket][WARNING] Failed to establish websocket connection: Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)
[05/16/2022 13:31:16][mattermostdriver.websocket][WARNING] Failed to establish websocket connection: Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)
[2022-05-16 13:31:16,893][mmpy.bot][INFO] Stopping bot.

**How To Reproduce**
To reproduce this, just create a site with ssl, and an empty enviroment just trying to run the following code

**Expected behavior**
I expected the client to connect to the bot and receive messages

**Operating Environment (please complete the following information):**
 - OS: Rhel 8
 - Python Version: [3.10

Here is my python code.
---------------------------------------------
>from mmpy_bot import Bot, Settings, ExamplePlugin, WebHookExample, Plugin, listen_to, Message
>import urllib3, ssl
>
>import socket
>#import ssl
>#ssl.PROTOCOL_TLS_SERVER
>from plugins import *
>
>print(ssl.SSLContext)
>print(ssl.SSLCertVerificationError)
>
>class MyPlugin(Plugin):
>    @listen_to("wake up")
>    async def wake_up(self, message: Message):
>        self.driver.reply_to(message, "I'm awake!")
>#from My_plugin import plugins #  <== Example of importing your own plugin, don't forget to add it to the plugins list.
>urllib3.disable_warnings()
>bot = Bot(
>    settings=Settings(
>        MATTERMOST_URL = 'https://URL.anses.gob.ar',
>        MATTERMOST_PORT = 443,
>        BOT_TOKEN = 'SECRET_TOKEN',
>        BOT_TEAM = 'DTyA',
>        SSL_VERIFY = True,
>    ),
>    plugins=[MyPlugin()],
>)
>bot.run()
--------------------------------------------

**Comment by attzonko** [comment] 2022-05-17 10:02
Are you using a reverse proxy? If so I would guess it has to do with that configuration...

**Comment by notrurs** [comment] 2022-07-28 07:34
Hi! Same issue. The problem in mattermostdriver. See its [issue](https://github.com/Vaelor/python-mattermost-driver/issues/115), it should help

**Comment by attzonko** [comment] 2022-07-31 13:46
Looks like your PR should fix it: https://github.com/Vaelor/python-mattermost-driver/pull/122

Once merged and released we should be able to get the fix.

**Comment by unode** [comment] 2022-08-29 09:08
As we moved to a different driver and a similar issue was fixed along the way, I'm closing this as outdated.
Please feel free to reopen if the issue is still present.

**Closed by unode** 2022-08-29 09:08 UTC
Labels: bug, question
