### ISSUE TITLE
TypeError during bot initialization

### ISSUE THREAD

**Issue by DaniilBut** [attzonko/mmpy_bot#556] opened 2024-12-09 14:56 UTC
Studying this framework, when trying to run a simple bot, I encounter an error Exception has occurred: TypeError
Client.__init__() got an unexpected keyword argument ‘proxies’
  File ‘C:\Users\dbute\Desktop\MattermostBot\bot.py’, line 6, in <module>
    bot = Bot(
          ^^^^
TypeError: Client.__init__() got an unexpected keyword argument ‘proxies’
bot.py:
```
# !/usr/bin/env python

from mmpy_bot import Bot, Settings
from my_plugin import MyPlugin

bot = Bot(
    settings=Settings(
        MATTERMOST_URL = ‘http://127.0.0.1/’,
        MATTERMOST_PORT = 8080,
        BOT_TOKEN = ‘4mm5nhyx6frizfrwarg9pbdbnh’,
        BOT_TEAM = ‘Test’,
    ),
    plugins=[MyPlugin()],
)
bot.run()
```
my_plugin.py:
```
import re
from mmpy_bot import Plugin, listen_to
from mmpy_bot import Message
class MyPlugin(Plugin):
    @listen_to(‘wake up’).
    async def wake_up(self, message: Message):
        self.driver.reply_to(message, ‘I'm awake!’)
```
Has anyone encountered this error?

**Comment by attzonko** [comment] 2024-12-09 21:27
Looks like a duplicate of #555

**Closed by attzonko** 2024-12-09 21:27 UTC
